### ISSUE TITLE
How to import the ouput model to blender?

### ISSUE THREAD

**Issue by jxl0131** [iamNCJ/NRHints#4]
Hi!
I want to use the output model of nrhints in blender. But i found the output model has no color in blender, like this:
![图片](https://github.com/iamNCJ/NRHints/assets/70733580/165fd0be-8eda-4612-ac68-6aca37b70ab2)
This is the first output model 'cat' in blender.
Did I do something wrong? I hope you can help me!

Best wishes.

**Comment by iamNCJ** [comment]
Hi! Thanks for your interest in our work. This is an expected behavior, our output 3D model only serves as a visualization/debugging information of our SDF field and has no color. As an end-to-end nerf-based method, the color/material information of our reconstructed objects is stored in the weights of the color net and is not factored into any material parameters.

**Comment by jxl0131** [comment]
> Hi! Thanks for your interest in our work. This is an expected behavior, our output 3D model only serves as a visualization/debugging information of our SDF field and has no color. As an end-to-end nerf-based method, the color/material information of our reconstructed objects is stored in the weights of the color net and is not factored into any material parameters.

Thank you for your reply!
So, if I want to directly use your network to rebuild a three -dimensional model with color, this is impossible, right?

**Comment by iamNCJ** [comment]
Yes, as our method is implicit. Maybe you can try to fit our model into an explicit material representation like GGX per point if you really want to use the explicit model.

**Comment by jxl0131** [comment]
> Yes, as our method is implicit. Maybe you can try to fit our model into an explicit material representation like GGX per point if you really want to use the explicit model.

Thank you for your reply. Can you say more about GGX? Or, can you recommend a NERF project that produces a 3-d model with color. Actually, I just need some nice nerf-generated models.

**Comment by iamNCJ** [comment]
I haven't surveyed much on these methods, but maybe you can refer to works like [nerf2mesh](https://me.kiui.moe/nerf2mesh/) and [nvdiffrec](https://nvlabs.github.io/nvdiffrec/), which might meet your need. These works have more restrictions on the object's shape and material but can output an explicit model.
